### ISSUE TITLE
[Proposal] Drift

### ISSUE THREAD

**Issue by nimbinatus** [pulumi/pulumitv#91]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Topic Proposal

What's drift?

### Show

Quick Bites

**Comment by rawkode** [comment]
I believe this can be closed now.

Episodes on [QuickBytes](https://www.youtube.com/watch?v=mclJwzMz_ek) and [Modern Infrastructure](https://www.youtube.com/watch?v=7nJBFEtqTl8&t=555s) now exist.

**Comment by nimbinatus** [comment]
yep!

**Comment by nimbinatus** [comment]
:eyeroll:
